# Generated by Django 5.1.3 on 2025-07-08 14:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("facility", "0001_initial"),
        ("utils", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=100)),
                ("unit_of_measurement", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of the asset category.", max_length=50
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the asset category.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the asset category.", max_length=100
                    ),
                ),
                (
                    "salvage_value_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salvage Value Percentage.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "useful_life_year",
                    models.IntegerField(
                        blank=True, help_text="Useful Life (years).", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the asset category.",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the asset subcategory.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the asset subcategory.", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of the asset subcategory.", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the asset subcategory.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this subcategory active?"
                    ),
                ),
                (
                    "asset_category",
                    models.ForeignKey(
                        help_text="The asset category this subcategory belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="asset_inventory.assetcategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "asset_name",
                    models.CharField(help_text="Name of the asset.", max_length=255),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("Asset", "Asset"), ("Consumable", "Consumable")],
                        default="Asset",
                        help_text="Type of the asset item.",
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("Used", "Used"), ("Brand New", "Brand New")],
                        help_text="Condition of the asset.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the asset was purchased.",
                        null=True,
                    ),
                ),
                (
                    "purchased_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount for which the asset was purchased.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique serial number of the asset.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        help_text="Unique asset tag identifier.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "lifespan",
                    models.CharField(
                        blank=True,
                        help_text="Expected lifespan of the asset (e.g., '5 years').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "oem_warranty",
                    models.TextField(
                        blank=True, help_text="Details of the OEM warranty.", null=True
                    ),
                ),
                (
                    "oem_warranty_en",
                    models.TextField(
                        blank=True, help_text="Details of the OEM warranty.", null=True
                    ),
                ),
                (
                    "oem_warranty_fr",
                    models.TextField(
                        blank=True, help_text="Details of the OEM warranty.", null=True
                    ),
                ),
                (
                    "oem_warranty_es",
                    models.TextField(
                        blank=True, help_text="Details of the OEM warranty.", null=True
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Building where the asset is located.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="facility.building",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility where the asset is located.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subsystem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subsystem where the asset is located.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="facility.subsystem",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zone where the asset is located.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="facility.zone",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category of the asset.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="asset_inventory.assetcategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subcategory of the asset.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="asset_inventory.assetsubcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="asset_inventory.manufacturer",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="asset_inventory.assetsubcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_references",
                        to="asset_inventory.assetcategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_references",
                        to="asset_inventory.assetsubcategory",
                    ),
                ),
                (
                    "inventory_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_references",
                        to="asset_inventory.inventorytype",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_references",
                        to="asset_inventory.manufacturer",
                    ),
                ),
                (
                    "model_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_references",
                        to="asset_inventory.modelreference",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Low Stock", "Low Stock"),
                            ("Out of Stock", "Out of Stock"),
                            ("Discontinued", "Discontinued"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("part_no", models.CharField(blank=True, max_length=100, null=True)),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Current quantity in stock",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Unit price in NGN",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "purchase_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("minimum_stock", models.PositiveIntegerField(default=0)),
                ("max_stock", models.PositiveIntegerField(default=0)),
                ("flags", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_categories",
                        to="asset_inventory.assetcategory",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_facility",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_subcategories",
                        to="asset_inventory.assetsubcategory",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_vendors",
                        to="accounts.vendor",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.inventorytype",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.modelreference",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the store.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the store.", max_length=255, unique=True
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Storage capacity of the store.",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Physical location or address of the store.",
                        null=True,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated facility for the store.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MovementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_no",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("movement_date", models.DateTimeField(auto_now_add=True)),
                ("transfer_quantity", models.IntegerField()),
                (
                    "transfer_unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "transfer_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asset_inventory.inventory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Move By",
                    ),
                ),
                (
                    "from_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movement_from_store",
                        to="asset_inventory.store",
                    ),
                ),
                (
                    "to_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movement_to_store",
                        to="asset_inventory.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("required_date", models.DateField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.assetcategory",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.assetsubcategory",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.inventorytype",
                    ),
                ),
                (
                    "request_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("invoice_number", models.CharField(editable=False, max_length=10)),
                ("required_date", models.DateField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("vendor", "Request from Vendor"),
                            ("store", "Request from Store"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "attachment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="personnel_documents",
                        to="utils.imageattachment",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.vendor",
                    ),
                ),
                ("items", models.ManyToManyField(to="asset_inventory.item")),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="asset_inventory.store",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("required_date", models.DateField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("transfer", "Transfer"), ("return", "Return")],
                        default="transfer",
                        help_text="Transfer type (transfer or return)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.category",
                    ),
                ),
                (
                    "confirmation_required_from",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who need to confirm this transfer",
                        related_name="transfer_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transfer_items",
                        to="asset_inventory.item",
                    ),
                ),
                (
                    "request_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Store or warehouse initiating the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_requests_from",
                        to="asset_inventory.store",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member making the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_requested_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.subcategory",
                    ),
                ),
                (
                    "transfer_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination store or warehouse",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_to_store",
                        to="asset_inventory.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="e.g == %(app_label)s_%(class)s",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the warehouse.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the warehouse.", max_length=100
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Storage capacity of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "capacity_en",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Storage capacity of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "capacity_fr",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Storage capacity of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "capacity_es",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Storage capacity of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the warehouse is currently active.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the warehouse.",
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Physical address of the warehouse.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated facility for the warehouse.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="store",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated warehouse for the store.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="asset_inventory.warehouse",
            ),
        ),
    ]
