# Generated by Django 5.1.3 on 2025-07-18 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('asset_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='name',
            field=models.CharField(default='New Inventory Request', max_length=100),
        ),
        migrations.CreateModel(
            name='ItemRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_inventory.item')),
                ('item_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_inventory.itemrequest')),
            ],
            options={
                'unique_together': {('item_request', 'item')},
            },
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='items',
            field=models.ManyToManyField(blank=True, through='asset_inventory.ItemRequestItem', to='asset_inventory.item'),
        ),
    ]
