# Generated by Django 5.1.3 on 2025-07-18 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0002_itemrequest_department_itemrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.assetcategory'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.assetsubcategory'),
        ),
    ]
