# Generated by Django 5.1.3 on 2025-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0003_alter_transfer_category_alter_transfer_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequest',
            name='type',
            field=models.CharField(choices=[('for_use', 'For Use'), ('for_store', 'For Store')], default='for_use', max_length=20),
        ),
    ]
