# Generated by Django 5.1.3 on 2025-07-20 19:06

import asset_inventory.models.item
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0004_alter_itemrequest_type'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.building'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='comment_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='comment_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a document (e.g., PDF, DOCX, etc.)', null=True, upload_to=asset_inventory.models.item.ItemRequest.upload_location),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.modelreference'),
        ),
    ]
