# Generated by Django 5.1.3 on 2025-07-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0005_itemrequest_building_itemrequest_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='model',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.assetcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.modelreference'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.assetsubcategory'),
        ),
    ]
