# Generated by Django 5.1.3 on 2025-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0007_remove_item_category_remove_item_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='description_en',
            field=models.TextField(blank=True, help_text='Detailed description of the asset category.', null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='description_es',
            field=models.TextField(blank=True, help_text='Detailed description of the asset category.', null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='description_fr',
            field=models.TextField(blank=True, help_text='Detailed description of the asset category.', null=True),
        ),
    ]
