# Generated by Django 5.1.3 on 2026-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0008_assetcategory_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='qr_code',
            field=models.CharField(blank=True, help_text='QR code identifier used to look up this asset on-site.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_SERVICE', 'In Service'), ('OUT_OF_SERVICE', 'Out of Service'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DECOMMISSIONED', 'Decommissioned')], default='IN_SERVICE', help_text='Operational status of the asset.', max_length=50),
        ),
    ]
