# Generated by Django 5.1.3 on 2026-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0009_asset_qr_code_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, help_text="Free-text location description for this specific asset, where it differs from its subsystem's name.", max_length=255, null=True),
        ),
    ]
