# Generated by Django 5.1.3 on 2025-07-08 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the apartment type (e.g., Studio, 1-bedroom, 2-bedroom, etc.).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated slug for the apartment type.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the building or flat.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the building or flat.", max_length=255
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "no",
                    models.CharField(
                        help_text="Unique number or identifier for the apartment.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of the apartment or room (e.g., 1-bedroom, studio).",
                        max_length=100,
                    ),
                ),
                (
                    "no_of_sqm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Size of the apartment in square meters (SQM).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description of the apartment.",
                        null=True,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("Freehold", "Freehold"),
                            ("Freehold (Leased Out)", "Freehold (Leased Out)"),
                            ("Leasehold", "Leasehold"),
                        ],
                        help_text="Ownership type of the apartment.",
                        max_length=50,
                    ),
                ),
                (
                    "service_power_charge_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start date for service or power charges.",
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Address of the apartment.", null=True
                    ),
                ),
                (
                    "bookable",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the apartment is bookable.",
                    ),
                ),
                (
                    "common_area",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the apartment is part of a common area.",
                    ),
                ),
                (
                    "available_for_lease",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the apartment is available for lease.",
                    ),
                ),
                (
                    "remit_lease_payment",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the apartment requires lease payments to be remitted.",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        help_text="Building or flat associated with this apartment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="facility.building",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the cluster.", max_length=255, unique=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "select_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for this cluster.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_clusters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code of the facility.", max_length=255, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the facility.", max_length=255, unique=True
                    ),
                ),
                (
                    "address_gps",
                    models.CharField(
                        blank=True,
                        help_text="GPS coordinates or detailed address of the facility.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the facility (e.g., 'Office', 'Warehouse', 'Retail').",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cluster to which this facility belongs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facility_cluster",
                        to="facility.cluster",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for this facility.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_facilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BulkNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the notification message.", max_length=255
                    ),
                ),
                (
                    "send_to_all_users",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send the notification to all users.",
                    ),
                ),
                (
                    "send_to_all_apartments",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send the notification to all apartments.",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Content of the notification message."),
                ),
                (
                    "send_as_email",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send the notification as an email.",
                    ),
                ),
                (
                    "send_as_sms",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send the notification as an SMS.",
                    ),
                ),
                (
                    "apartments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apartments or rooms associated with the notification.",
                        related_name="bulk_notifications",
                        to="facility.apartment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="e.g == %(app_label)s_%(class)s",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users to whom the notification is sent.",
                        related_name="bulk_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility_locations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Facilities or locations associated with the notification.",
                        related_name="bulk_notifications",
                        to="facility.facility",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="building",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="facility associated with this building (optional).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="facility.facility",
            ),
        ),
        migrations.CreateModel(
            name="FacilityInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Rent", "Rent"),
                            ("Maintenance", "Maintenance"),
                            ("Utility", "Utility"),
                            ("Other", "Other"),
                        ],
                        help_text="Type of invoice.",
                        max_length=50,
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        help_text="Client associated with the invoice.", max_length=255
                    ),
                ),
                (
                    "vat_no",
                    models.CharField(
                        blank=True,
                        help_text="VAT number for the invoice.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tin_no",
                    models.CharField(
                        blank=True,
                        help_text="TIN number for the invoice.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "purchase_order_no",
                    models.CharField(
                        blank=True,
                        help_text="Purchase order number for this invoice.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="Payment terms for this invoice.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "bank_account_currency",
                    models.CharField(
                        help_text="Bank account and currency associated with the payment.",
                        max_length=255,
                    ),
                ),
                (
                    "expected_payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected payment date for the invoice.",
                        null=True,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        help_text="Template used for this invoice.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Payment Pending", "Payment Pending"),
                            ("Part Paid", "Part Paid"),
                            ("Paid", "Paid"),
                        ],
                        default="Payment Pending",
                        help_text="Status of the invoice payment.",
                        max_length=50,
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        blank=True, help_text="Details about the payment.", null=True
                    ),
                ),
                (
                    "client_address",
                    models.TextField(
                        blank=True, help_text="Address of the client.", null=True
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        help_text="Facility or location associated with this invoice.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.facility",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="e.g == %(app_label)s_%(class)s",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Quantity of the item."),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit of the item.",
                        max_digits=10,
                    ),
                ),
                (
                    "vatable",
                    models.BooleanField(
                        default=False, help_text="Indicates if the item is vatable."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item.", null=True
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facility.facilityinvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "withholding_tax",
                    models.CharField(
                        blank=True,
                        help_text="Withholding tax applicable to this payment.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date of the payment.", null=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        help_text="Mode of payment (e.g., Bank transfer, Cash).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid in this transaction.",
                        max_digits=10,
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional remarks about the payment.",
                        null=True,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bank account used for this payment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.bankaccount",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="Invoice this payment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="facility.facilityinvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the landlord.", max_length=255, unique=True
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Address of the landlord.", null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the landlord.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the landlord.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="apartment",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                help_text="Landlord associated with this apartment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apartments",
                to="facility.landlord",
            ),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the region.", max_length=255, unique=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country where the region is located.", max_length=100
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "select_manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for this region.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_regions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cluster",
            name="region",
            field=models.ForeignKey(
                help_text="Region to which this cluster belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="facility.region",
            ),
        ),
        migrations.CreateModel(
            name="Subsystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the space or sub-system.", max_length=255
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        help_text="Building or system to which this space or sub-system belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces_subsystems",
                        to="facility.building",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="facility associated with this space/sub-system (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the zone.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the zone.", max_length=255),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="facility associated with this zone (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facility_zones",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="building",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                help_text="Zone associated with the building.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="facility.zone",
            ),
        ),
    ]
