# Generated by Django 5.1.3 on 2026-09-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsystem',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Building to which this space or sub-system belongs (optional — some sites track spaces directly under a zone with no building).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces_subsystems', to='facility.building'),
        ),
    ]
