# Generated by Django 5.1.3 on 2026-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_alter_subsystem_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='location',
            field=models.CharField(blank=True, help_text='Free-text location description, where it differs from the name (e.g. a wing or floor).', max_length=255, null=True),
        ),
    ]
