# Generated by Django 5.1.3 on 2026-09-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_subsystem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone this space/sub-system belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsystems', to='facility.zone'),
        ),
    ]
