# Generated by Django 5.1.3 on 2026-09-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_subsystem_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsystem',
            name='location',
        ),
    ]
