# Generated by Django 5.1.3 on 2025-07-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("asset_inventory", "0001_initial"),
        ("facility", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount associated with the item.",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the item.", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "assign_escalate",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the follow-up involves assignment or escalation.",
                    ),
                ),
                (
                    "notify_requester",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the requester is notified.",
                    ),
                ),
                (
                    "cc",
                    models.TextField(
                        blank=True,
                        help_text="Users or email addresses to CC.",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Message content for the follow-up."),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Attachment for the follow-up.",
                        null=True,
                        upload_to="followups/",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        help_text="Invoice number for the cost item.", max_length=100
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Nigerian Naira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        help_text="Currency of the cost.",
                        max_length=3,
                    ),
                ),
                (
                    "add_discount",
                    models.BooleanField(
                        default=False, help_text="Whether a discount is added."
                    ),
                ),
                (
                    "exclude_in_management_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude this cost in management fee calculations.",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "requisition_date",
                    models.DateField(help_text="Date of the payment record."),
                ),
                (
                    "requisition_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expected_payment_date",
                    models.DateField(
                        blank=True, help_text="Expected payment date.", null=True
                    ),
                ),
                (
                    "retirement",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the payment is for retirement purposes.",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="Additional remarks for the payment.",
                        null=True,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("request", "Request Approval"),
                            ("approve", "Approve"),
                        ],
                        default="request",
                        help_text="Approval status for the payment.",
                        max_length=10,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="User comments regarding the payment.",
                        null=True,
                    ),
                ),
                (
                    "withholding_tax",
                    models.CharField(
                        blank=True,
                        help_text="Selected withholding tax option.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "expected_payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Expected payment amount for this requisition.",
                        max_digits=12,
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Items linked to this payment requisition.",
                        related_name="payment_items",
                        to="work.paymentitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_to",
                    models.ForeignKey(
                        help_text="User or entity to whom the payment is made.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_user",
                        to="accounts.vendor",
                    ),
                ),
                (
                    "request_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users to whom the payment approval requests are sent.",
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_notification",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether to send a notification for this comment.",
                    ),
                ),
                ("message", models.TextField(help_text="Comment message.")),
                (
                    "internal_only",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the comment is for internal use only.",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="File attachment for the comment.",
                        null=True,
                        upload_to="comments/",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="Payment associated with the comment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="work.paymentrequisition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PPM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Describe this maintenance task."),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        help_text="Frequency of maintenance (e.g., in days)."
                    ),
                ),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("Hours", "Hour(s)"),
                            ("Days", "Day(s)"),
                            ("Weeks", "Week(s)"),
                            ("Months", "Month(s)"),
                        ],
                        help_text="Frequency unit (e.g., hours, days).",
                        max_length=10,
                    ),
                ),
                (
                    "notify_before_due",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of days/hours before notifying the responsible team.",
                        null=True,
                    ),
                ),
                (
                    "notify_unit",
                    models.CharField(
                        choices=[
                            ("Hours", "Hour(s)"),
                            ("Days", "Day(s)"),
                            ("Weeks", "Week(s)"),
                            ("Months", "Month(s)"),
                        ],
                        help_text="Unit of notification (e.g., hours, days).",
                        max_length=10,
                    ),
                ),
                (
                    "send_reminder_every",
                    models.IntegerField(
                        blank=True,
                        help_text="Frequency of reminders before the due date (e.g., in days).",
                        null=True,
                    ),
                ),
                (
                    "reminder_unit",
                    models.CharField(
                        choices=[
                            ("Hours", "Hour(s)"),
                            ("Days", "Day(s)"),
                            ("Weeks", "Week(s)"),
                            ("Months", "Month(s)"),
                        ],
                        help_text="Unit for reminders.",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Nigerian Naira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="NGN",
                        help_text="Currency for associated costs.",
                        max_length=3,
                    ),
                ),
                (
                    "auto_create_work_order",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically create a work order for this PPM.",
                    ),
                ),
                (
                    "create_work_order_as_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically approve the created work order.",
                    ),
                ),
                (
                    "activities_safety_tips",
                    models.TextField(
                        blank=True,
                        help_text="Activities or safety tips related to the maintenance task.",
                        null=True,
                    ),
                ),
                (
                    "apartments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apartments or rooms associated with the maintenance.",
                        related_name="ppms",
                        to="facility.apartment",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Assets involved in the maintenance.",
                        related_name="ppms",
                        to="asset_inventory.asset",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of the maintenance task.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.category",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Facilities associated with the maintenance.",
                        related_name="ppms",
                        to="facility.facility",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Items required for this maintenance task.",
                        related_name="ppms",
                        to="work.paymentitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subcategory of the maintenance task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "PPM",
                "verbose_name_plural": "PPM)",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Unplanned", "Unplanned"), ("Planned", "Planned")],
                        help_text="Type of the work order.",
                        max_length=50,
                    ),
                ),
                (
                    "work_order_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique 7-digit work request number.",
                        max_length=7,
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        blank=True,
                        help_text="Sub-type of the work order.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        help_text="Priority level of the work order.",
                        max_length=50,
                    ),
                ),
                (
                    "ppm_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Unscheduled", "Unscheduled"),
                        ],
                        help_text="Planned Preventive Maintenance type.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the work order.",
                        null=True,
                    ),
                ),
                (
                    "expected_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected start date for the work.",
                        null=True,
                    ),
                ),
                (
                    "expected_start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Expected start time for the work.",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Expected duration of the work.",
                        null=True,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the work order is approved.",
                    ),
                ),
                (
                    "mobilization_fee_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether mobilization fee is required.",
                    ),
                ),
                (
                    "po_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether a purchase order is required.",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the request is approved.",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, help_text="Remark for the approval.", null=True
                    ),
                ),
                (
                    "item_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost of the item.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "payment_requisition",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a payment requisition should be created.",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        help_text="Approval status of the work order.",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("NGN", "NGN")],
                        default="USD",
                        help_text="Currency for the work order.",
                        max_length=3,
                    ),
                ),
                (
                    "exclude_management_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the management fee should be excluded.",
                    ),
                ),
                (
                    "add_discount",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a discount should be applied.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated unique slug for the work order.",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "require_mobilization_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a Mobilization Fee is required for the work order.",
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for follow-ups related to the work order.",
                        null=True,
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True,
                        help_text="Invoice number associated with the work order.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apartment/Room related to the work order.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders_apartment",
                        to="facility.apartment",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset associated with the work order.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_assets",
                        to="asset_inventory.asset",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category of the work order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department handling the work order.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.department",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        help_text="Facility or location associated with the work order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders_facility",
                        to="facility.facility",
                    ),
                ),
                (
                    "follow_up",
                    models.ForeignKey(
                        blank=True,
                        help_text="Follow-up details.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work.followup",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_to",
                    models.ForeignKey(
                        help_text="User to whom the approval request is sent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User who requested the work order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subcategory of the work order.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders_subcategory",
                        to="accounts.subcategory",
                    ),
                ),
                (
                    "work_owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User responsible for the work order.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
            },
        ),
        migrations.AddField(
            model_name="paymentrequisition",
            name="work_orders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Work orders linked to the payment.",
                related_name="linked_payments",
                to="work.workorder",
            ),
        ),
        migrations.AddField(
            model_name="paymentitem",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Work order linked to the item.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_items",
                to="work.workorder",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="work_order_completions/"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="work.workorder",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Type of the work request.", max_length=255
                    ),
                ),
                (
                    "work_request_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique 7-digit work request number.",
                        max_length=7,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated unique slug for the work request.",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "require_mobilization_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a Mobilization Fee is required for the request.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the work request.",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Medium",
                        help_text="Priority level of the work request.",
                        max_length=10,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="File attachment for the work request.",
                        null=True,
                        upload_to="work_requests/attachments/",
                    ),
                ),
                ("require_quotation", models.BooleanField(default=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        help_text="Approval status of the work request.",
                        max_length=10,
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes for follow-ups related to the work request.",
                        null=True,
                    ),
                ),
                (
                    "payment_requisition",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a payment requisition should be created.",
                    ),
                ),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True,
                        help_text="Invoice number associated with the work request.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("NGN", "NGN")],
                        default="USD",
                        help_text="Currency for the work request.",
                        max_length=3,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost of the work request.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "add_discount",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if a discount should be applied.",
                    ),
                ),
                (
                    "exclude_management_fee",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the management fee should be excluded.",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset associated with the work request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests_assets",
                        to="asset_inventory.asset",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="building associated with the work request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests_buildings",
                        to="facility.building",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category of the work request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests",
                        to="accounts.category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department associated with the work request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests",
                        to="accounts.department",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facility associated with the work request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests",
                        to="facility.facility",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="e.g == %(app_label)s_%(class)s",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who made the request.",
                        related_name="work_request_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subcategory of the work request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_requests",
                        to="accounts.subcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
