# Generated by Django 5.1.3 on 2025-07-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0007_remove_item_category_remove_item_model_and_more'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrequest',
            name='status',
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the work request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='asset_inventory.assetcategory'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory of the work request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='asset_inventory.assetsubcategory'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='type',
            field=models.CharField(choices=[('Work', 'Work'), ('Procument', 'Procument')], help_text='Type of the work request.', max_length=255),
        ),
    ]
