# Generated by Django 5.1.3 on 2026-05-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_workrequest_status_alter_workrequest_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User assigned to approve this work request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to review this work request.', related_name='work_requests_to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
