# Generated by Django 5.1.3 on 2026-05-13 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_roles'),
        ('facility', '0001_initial'),
        ('work', '0004_workrequest_reviewer_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User assigned to approve this work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Building associated with the work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_building', to='facility.building'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of the work order.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to review this work order.', related_name='work_orders_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_ppm',
            field=models.ForeignKey(blank=True, help_text='PPM schedule this order was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_work_orders', to='work.ppm'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_work_request',
            field=models.ForeignKey(blank=True, help_text='Work request this order was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_work_orders', to='work.workrequest'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_category', to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility or location associated with the work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_facility', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Priority level of the work order.', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='request_to',
            field=models.ForeignKey(blank=True, help_text='User to whom the approval request is sent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='type',
            field=models.CharField(blank=True, choices=[('Unplanned', 'Unplanned'), ('Planned', 'Planned'), ('FROM-PPM', 'From PPM'), ('FROM-WORK-REQUEST', 'From Work Request'), ('RAISE-PAYMENT', 'Raise Payment')], help_text='Type of the work order.', max_length=50, null=True),
        ),
    ]
