# Generated by Django 5.1.3 on 2026-05-13 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0008_assetcategory_description_en_and_more'),
        ('work', '0006_ppm_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppm',
            name='category',
            field=models.ForeignKey(help_text='Category of the maintenance task.', on_delete=django.db.models.deletion.CASCADE, to='asset_inventory.assetcategory'),
        ),
        migrations.AlterField(
            model_name='ppm',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory of the maintenance task.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset_inventory.assetsubcategory'),
        ),
    ]
