# Generated by Django 5.1.3 on 2026-05-13 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_ppm_buildings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ppm',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User responsible for approving this PPM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppm_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
