# Generated by Django 5.1.3 on 2026-05-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_inventory', '0008_assetcategory_description_en_and_more'),
        ('work', '0009_ppm_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_category', to='asset_inventory.assetcategory'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory of the work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_subcategory', to='asset_inventory.assetsubcategory'),
        ),
    ]
