import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_workorder_use_asset_categories'),
        ('accounts', '0006_alter_user_roles'),
    ]

    operations = [
        # Remove old field merged into unified approval_status
        migrations.RemoveField(
            model_name='workrequest',
            name='reviewer_approval_status',
        ),
        # Expand approval_status choices and increase max_length
        migrations.AlterField(
            model_name='workrequest',
            name='approval_status',
            field=models.CharField(
                choices=[
                    ('Pending Review', 'Pending Review'),
                    ('CP Approved', 'CP Approved'),
                    ('Reviewed', 'Reviewed'),
                    ('Fully Approved', 'Fully Approved'),
                    ('Rejected – Vendor Changed', 'Rejected – Vendor Changed'),
                    ('Reviewer Rejected', 'Reviewer Rejected'),
                    ('Approver Rejected', 'Approver Rejected'),
                ],
                default='Pending Review',
                max_length=30,
                help_text='Current workflow status of the work request.',
            ),
        ),
        # Vendor invoice uploaded by Requester
        migrations.AddField(
            model_name='workrequest',
            name='vendor_invoice',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='work_requests/vendor_invoices/',
                help_text="Invoice from the vendor, uploaded by the Requester.",
            ),
        ),
        # Original vendor from the Requester's invoice
        migrations.AddField(
            model_name='workrequest',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='work_requests_original_vendor',
                to='accounts.vendor',
                help_text="Original vendor from the Requester's invoice.",
            ),
        ),
        # Lock flag
        migrations.AddField(
            model_name='workrequest',
            name='is_locked',
            field=models.BooleanField(
                default=False,
                help_text='Locked after submission. Unlocked only when rejected for correction.',
            ),
        ),
        # PO number generated by Procurement & Store
        migrations.AddField(
            model_name='workrequest',
            name='po_number',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                help_text='Generated Purchase Order number.',
            ),
        ),
        # Vendor on the PO (may differ from original)
        migrations.AddField(
            model_name='workrequest',
            name='po_vendor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='work_requests_po_vendor',
                to='accounts.vendor',
                help_text='Vendor on the PO (may differ from the original vendor).',
            ),
        ),
        # Rejection reasons (mandatory per role)
        migrations.AddField(
            model_name='workrequest',
            name='cp_reason',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Mandatory reason entered by Procurement & Store when changing vendor.',
            ),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='reviewer_reason',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Mandatory reason provided when Reviewer rejects.',
            ),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='approver_reason',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Mandatory reason provided when Approver rejects.',
            ),
        ),
        # Final approval fields
        migrations.AddField(
            model_name='workrequest',
            name='digital_signature',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=255,
                help_text="Approver's digital signature on final approval.",
            ),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='fully_approved_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Timestamp when request was fully approved and committed to the ledger.',
            ),
        ),
    ]
