# Generated by Django 5.1.3 on 2026-06-04 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_roles'),
        ('facility', '0001_initial'),
        ('work', '0012_workrequest_number_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department handling the work order.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User assigned to give final approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='attachment',
            field=models.FileField(blank=True, help_text='General file attachment for the work request.', null=True, upload_to='work_requests/attachments/'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Building associated with the work request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests_buildings', to='facility.building'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='request_to',
            field=models.ManyToManyField(blank=True, help_text='Procurement & Store handler(s) assigned to audit this request.', related_name='work_request_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
