# Generated by Django 5.1.3 on 2026-06-09 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_workorder_allow_resubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workordercompletion',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Reviewer Rejected', 'Reviewer Rejected'), ('Approver Rejected', 'Approver Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='approver_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='reviewer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='completions_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordercompletion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
