# Generated by Django 5.1.3 on 2026-06-09 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        ('work', '0019_workordercompletion_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=30)),
                ('tracker_status', models.CharField(default='Pending', max_length=30)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Reviewer Rejected', 'Reviewer Rejected'), ('Approver Rejected', 'Approver Rejected')], default='Pending', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('approver_notes', models.TextField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_to_approve', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='facility.facility')),
                ('owner', models.ForeignKey(blank=True, help_text='e.g == %(app_label)s_%(class)s', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_raised', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, related_name='invoices_to_review', to=settings.AUTH_USER_MODEL)),
                ('work_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='work.workordercompletion')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='work.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='work.invoice')),
            ],
        ),
    ]
