# Generated by Django 5.1.3 on 2026-09-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_roles'),
        ('work', '0021_notification_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequisition',
            name='payee_owner',
            field=models.ForeignKey(blank=True, help_text="Owner/requester to pay, when payee_type='owner'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_payment_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequisition',
            name='payee_personnel',
            field=models.ForeignKey(blank=True, help_text="Personnel to pay, when payee_type='personnel'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requisitions', to='accounts.personnel'),
        ),
        migrations.AddField(
            model_name='paymentrequisition',
            name='payee_type',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('personnel', 'Personnel'), ('owner', 'Owner')], help_text='Who this payment is made to: a Vendor, Personnel, or the requesting Owner.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', help_text='Closed/Pending/Rejected tracking of the physical work, separate from approval_status. Managed via the set-status action.', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrequisition',
            name='pay_to',
            field=models.ForeignKey(blank=True, help_text="Vendor to pay, when payee_type='vendor'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_user', to='accounts.vendor'),
        ),
    ]
