# Generated by Django 5.1.3 on 2026-09-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_remove_subsystem_location'),
        ('work', '0022_paymentrequisition_payee_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='subsystem',
            field=models.ForeignKey(blank=True, help_text='Subsystem (subzone/space) associated with the work request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='facility.subsystem'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Zone associated with the work request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_requests', to='facility.zone'),
        ),
    ]
