# Generated by Django 5.1.3 on 2025-07-21 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='type_es',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='type_fr',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_contact_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='type',
            field=models.CharField(choices=[('Item', 'Item'), ('Service', 'Service')], max_length=20),
        ),
    ]
