# Generated by Django 5.1.3 on 2025-07-21 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_purchaseorder_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='title',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='e.g == %(app_label)s_%(class)s', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
