# Generated by Django 5.1.3 on 2025-11-10 20:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_access_to_all_flats_remove_user_flats_and_more'),
        ('facility', '0001_initial'),
        ('procurement', '0003_remove_purchaseorder_title_purchaseorder_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grncomment',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='grncomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grnitem',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisitionapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisitionapproval',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisitioncomment',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisitioncomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisitionitem',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisitionpayment',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='rfqapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='rfqapproval',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqcomment',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='requested_date',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='requested_time',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednote',
            name='store',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='expected_payment_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='remark_en',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='remark_es',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='remark_fr',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequisition',
            name='withholding_tax',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='deadline_time',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='status',
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='date_of_receipt',
            field=models.DateField(default=datetime.date.today, help_text='Date goods were received.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='delivery_note_number',
            field=models.CharField(blank=True, help_text="Vendor's delivery reference number.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='grn_number',
            field=models.CharField(blank=True, help_text='Auto-generated GRN number with format GRN-000000.', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='invoice_number',
            field=models.CharField(blank=True, help_text="Vendor's invoice reference number.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor who delivered the goods.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='type_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='type_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='type_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount of the requisition.', max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='description',
            field=models.TextField(default='', help_text='Description of the purchase requisition.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='description_en',
            field=models.TextField(help_text='Description of the purchase requisition.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='description_es',
            field=models.TextField(help_text='Description of the purchase requisition.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='description_fr',
            field=models.TextField(help_text='Description of the purchase requisition.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.date.today, help_text='Expected delivery date.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='sage_reference_number',
            field=models.CharField(blank=True, help_text='SAGE reference number (optional).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='title',
            field=models.CharField(default='', help_text='Title of the purchase requisition.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='title_en',
            field=models.CharField(help_text='Title of the purchase requisition.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='title_es',
            field=models.CharField(help_text='Title of the purchase requisition.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderrequisition',
            name='title_fr',
            field=models.CharField(help_text='Title of the purchase requisition.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='User who requested the RFQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='terms_en',
            field=models.TextField(blank=True, help_text='Terms and conditions.', null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='terms_es',
            field=models.TextField(blank=True, help_text='Terms and conditions.', null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='terms_fr',
            field=models.TextField(blank=True, help_text='Terms and conditions.', null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='title_en',
            field=models.CharField(help_text='Title of the RFQ.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='title_es',
            field=models.CharField(help_text='Title of the RFQ.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='title_fr',
            field=models.CharField(help_text='Title of the RFQ.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility where goods were received.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_facility', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Reference to the original Purchase Order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received_notes', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='User who received the goods (All Requester).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequisition',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Auto-generated invoice number with format INV-000000.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderrequisition',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor for the requisition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_requisitions', to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='currency',
            field=models.CharField(help_text='Currency for the RFQ.', max_length=10),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Requester facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='facility.facility'),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions.', null=True),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='title',
            field=models.CharField(help_text='Title of the RFQ.', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='type',
            field=models.CharField(choices=[('IFM Services', 'IFM Services'), ('Supply', 'Supply'), ('General Services', 'General Services'), ('Other Services', 'Other Services')], help_text='Type of RFQ.', max_length=100),
        ),
        migrations.CreateModel(
            name='VendorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('contract_title', models.CharField(help_text='Contract title.', max_length=255)),
                ('contract_title_en', models.CharField(help_text='Contract title.', max_length=255, null=True)),
                ('contract_title_fr', models.CharField(help_text='Contract title.', max_length=255, null=True)),
                ('contract_title_es', models.CharField(help_text='Contract title.', max_length=255, null=True)),
                ('contract_type', models.CharField(choices=[('Service', 'Service'), ('Purchase', 'Purchase'), ('Lease', 'Lease'), ('NDA', 'NDA')], help_text='Type of contract.', max_length=50)),
                ('start_date', models.DateField(help_text='Contract start date.')),
                ('end_date', models.DateField(help_text='Contract end date.')),
                ('proposed_value', models.DecimalField(decimal_places=2, help_text='Proposed contract value.', max_digits=15)),
                ('owner', models.ForeignKey(blank=True, help_text='e.g == %(app_label)s_%(class)s', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='User assigned to review the contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contracts', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Selected vendor for the contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_contracts', to='accounts.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Contract',
                'verbose_name_plural': 'Vendor Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GRNApproval',
        ),
        migrations.DeleteModel(
            name='GRNComment',
        ),
        migrations.DeleteModel(
            name='GRNItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderRequisitionApproval',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderRequisitionComment',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderRequisitionItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderRequisitionPayment',
        ),
        migrations.DeleteModel(
            name='RFQApproval',
        ),
        migrations.DeleteModel(
            name='RFQComment',
        ),
        migrations.DeleteModel(
            name='RFQItem',
        ),
    ]
