# Generated by Django 5.1.3 on 2025-07-08 14:53

import accounts.models.personnels
import accounts.models.users
import accounts.models.vendors
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for the user.",
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the user.", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the user.", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slugified identifier for the user.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "roles",
                    models.CharField(
                        choices=[
                            ("Super Admin", "Super Admin"),
                            ("Facility Admin", "Facility Admin"),
                            ("Facility Procurement", "Facility Procurement"),
                            ("Facility Manager", "Facility Manager"),
                            ("Facility Officer", "Facility Officer"),
                            ("Facility Auditor", "Facility Auditor"),
                            ("Facility Account", "Facility Account"),
                            ("Facility Store", "Facility Store"),
                            ("Facility View", "Facility View"),
                        ],
                        default="Super Admin",
                        help_text="Type of user.",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the user.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the user.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="Designation of the user.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Date of birth of the user.", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        help_text="Gender of the user.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        help_text="Nationality of the user.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        help_text="Passport number of the user.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the user.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the user.",
                        max_length=10,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatar.png",
                        help_text="Profile of the user",
                        null=True,
                        upload_to=accounts.models.users.User.upload_location,
                    ),
                ),
                ("team_lead", models.BooleanField(default=False)),
                ("generate_reports", models.BooleanField(default=False)),
                (
                    "approval_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Approval limit for the user.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date and time the user joined."
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True, help_text="Last login date and time."
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Indicates if the user is verified."
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False, help_text="Indicates if the user is blocked."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the user account is active.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user is a staff member.",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, help_text="Indicates if the user is an admin."
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False, help_text="Indicates if the user is a superuser."
                    ),
                ),
                (
                    "access_to_all_facilities",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all facilities.",
                    ),
                ),
                (
                    "access_to_all_flats",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all flats.",
                    ),
                ),
                (
                    "access_to_all_apartments",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all apartments.",
                    ),
                ),
                (
                    "access_to_all_categories",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all assets categories.",
                    ),
                ),
                (
                    "access_to_all_warehouses",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all warehouses.",
                    ),
                ),
                (
                    "access_to_all_clients",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all clients.",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        help_text="The bank associated with the account.",
                        max_length=255,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="Name of the account holder.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slugified identifier for the user.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Account number for the bank account.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Nigerian Naira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        help_text="Currency associated with the account.",
                        max_length=50,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Address associated with the account.",
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the account.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the category.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the category.", null=True
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, help_text="Description of the category.", null=True
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, help_text="Description of the category.", null=True
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True, help_text="Description of the category.", null=True
                    ),
                ),
                (
                    "problem_type",
                    models.TextField(
                        blank=True,
                        help_text="Defines the problem type associated with this category.",
                        null=True,
                    ),
                ),
                (
                    "problem_type_en",
                    models.TextField(
                        blank=True,
                        help_text="Defines the problem type associated with this category.",
                        null=True,
                    ),
                ),
                (
                    "problem_type_fr",
                    models.TextField(
                        blank=True,
                        help_text="Defines the problem type associated with this category.",
                        null=True,
                    ),
                ),
                (
                    "problem_type_es",
                    models.TextField(
                        blank=True,
                        help_text="Defines the problem type associated with this category.",
                        null=True,
                    ),
                ),
                (
                    "work_request_approved",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("create_work_order", "Create work order"),
                            ("close_work_request", "Close work request"),
                        ],
                        help_text="Defines the action to be taken when a work request is approved.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "exclude_costing_limit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to exclude costing limit for this category.",
                    ),
                ),
                (
                    "power",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this category has power configurations.",
                    ),
                ),
                (
                    "create_payment_requisition",
                    models.BooleanField(
                        default=False,
                        help_text="Determines if payment requisition is auto-created for this category.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique slug for the client.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Company", "Company")],
                        help_text="Type of the client (Individual or Company).",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the client.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the client.", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the client.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number of the client.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Group the client belongs to.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Address of the client.", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the contact person.", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Last name of the contact person.", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the contact person.", max_length=60
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the contact person.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the contact.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Contact's first name.", max_length=255),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Contact's last name.", max_length=255),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact's phone number.", max_length=15
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact's email address.", max_length=254
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(help_text="Contract number.", max_length=50),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the contract."),
                ),
                ("end_date", models.DateField(help_text="End date of the contract.")),
                (
                    "access_to_all_facilities",
                    models.BooleanField(
                        default=False, help_text="Access to all facilities."
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Attachment file.",
                        null=True,
                        upload_to=accounts.models.vendors.Contract.contract_upload_location,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the department.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the department.", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the user.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the user.",
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Document file.",
                        upload_to=accounts.models.vendors.Document.document_upload_location,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the document.", null=True
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, help_text="Description of the document.", null=True
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True, help_text="Description of the document.", null=True
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True, help_text="Description of the document.", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=36, unique=True)),
                ("is_onboarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "staff_number",
                    models.CharField(
                        help_text="Unique identifier for the personnel.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique slugified identifier for the user.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the personnel.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number of the personnel.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatar.png",
                        help_text="Profile picture of the personnel.",
                        null=True,
                        upload_to=accounts.models.personnels.Personnel.avatar_upload_location,
                    ),
                ),
                (
                    "access_to_all_categories",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has access to all wos categories.",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the subcategory.",
                        null=True,
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the subcategory.",
                        null=True,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True,
                        help_text="Description of the subcategory.",
                        null=True,
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Description of the subcategory.",
                        null=True,
                    ),
                ),
                (
                    "exclude_costing_limit",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to exclude costing limit for this subcategory.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        help_text="Status of the subcategory.",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "Sub Category",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the unit of measurement.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the unit of measurement.",
                        null=True,
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the unit of measurement.",
                        null=True,
                    ),
                ),
                (
                    "description_fr",
                    models.TextField(
                        blank=True,
                        help_text="Description of the unit of measurement.",
                        null=True,
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Description of the unit of measurement.",
                        null=True,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Symbol representing the unit of measurement.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Area", "Area"),
                            ("Packing", "Packing"),
                            ("Piece", "Piece"),
                            ("Time", "Time"),
                            ("Volume", "Volume"),
                            ("Weight", "Weight"),
                            ("Other", "Other"),
                        ],
                        help_text="Type of the unit of measurement.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the client.",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Vendor's name.", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Company", "Company")],
                        help_text="Type of vendor.",
                        max_length=50,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "phone",
                    models.CharField(help_text="Vendor's phone number.", max_length=15),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Vendor's email address.",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(help_text="Bank account name.", max_length=255),
                ),
                ("bank", models.CharField(help_text="Bank name.", max_length=255)),
                (
                    "account_number",
                    models.CharField(
                        help_text="Bank account number.", max_length=20, unique=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Nigerian Naira"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        help_text="Account currency.",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
