# Generated by Django 5.1.3 on 2025-07-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apartments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Apartments the user is assigned to.",
                related_name="users_apartments",
                to="facility.apartment",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="facility",
            field=models.ManyToManyField(
                blank=True,
                help_text="Facilities the user is assigned to.",
                related_name="users_facilities",
                to="facility.facility",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="flats",
            field=models.ManyToManyField(
                blank=True,
                help_text="Flats the user is assigned to.",
                related_name="users_flats",
                to="facility.building",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor of the user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
