# Generated by Django 5.1.3 on 2025-07-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("asset_inventory", "0001_initial"),
        ("facility", "0001_initial"),
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="warehouse",
            field=models.ManyToManyField(
                blank=True,
                help_text="Warehouses the user is assigned to.",
                related_name="users_warehouses",
                to="asset_inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Asset categories the user is assigned to.",
                related_name="users_categories",
                to="accounts.category",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Clients the user is assigned to.",
                related_name="users_clients",
                to="accounts.client",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Contacts associated with this client.",
                related_name="clients",
                to="accounts.contact",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="onboarding",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Work Order categories the user is assigned to.",
                related_name="personnel_categories",
                to="accounts.category",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="personnel_documents",
                to="utils.fileattachment",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                help_text="The facility the personnel is assigned to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facility.facility",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="user",
            field=models.ForeignKey(
                help_text="e.g == %(app_label)s_%(class)s",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                help_text="Category to which the subcategory belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.category",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unitofmeasurement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="e.g == %(app_label)s_%(class)s",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
