# Generated by Django 5.1.3 on 2025-07-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="access_to_all_flats",
        ),
        migrations.RemoveField(
            model_name="user",
            name="flats",
        ),
        migrations.AddField(
            model_name="user",
            name="access_to_all_buildings",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user has access to all buildings.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="buildings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Buildings the user is assigned to.",
                related_name="users_buildings",
                to="facility.building",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Username for the user (auto-generated from email).",
                max_length=60,
                unique=True,
            ),
        ),
    ]
