# Generated by Django 5.1.3 on 2026-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_access_to_all_flats_remove_user_flats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Super Admin', 'SUPER_ADMIN'), ('Admin', 'ADMIN'), ('Requester', 'REQUESTER'), ('Reviewer', 'REVIEWER'), ('Approver', 'APPROVER'), ('Procurement and store', 'PROCUREMENT AND STORE')], default='Facility View', help_text='Type of user.', max_length=50),
        ),
    ]
