# Generated by Django 5.1.3 on 2026-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('SUPER ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('REQUESTER', 'Requester'), ('REVIEWER', 'Reviewer'), ('APPROVER', 'Approver'), ('PROCUREMENT AND STORE', 'Procurement and store')], default='Facility View', help_text='Type of user.', max_length=50),
        ),
    ]
