# Generated by Django 5.1.3 on 2025-06-24 10:11

import django.db.models.deletion
import utils.models.attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.models.attachment.file_upload_location
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.ImageField(
                        upload_to=utils.models.attachment.image_upload_location,
                        verbose_name="Image",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("object_id", models.PositiveIntegerField()),
                ("field_name", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "language"],
                        name="utils_trans_content_47b826_idx",
                    )
                ],
                "unique_together": {
                    ("content_type", "object_id", "field_name", "language")
                },
            },
        ),
    ]
