# Generated by Django 5.1.3 on 2026-09-01 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at login time, when available.', null=True)),
                ('user', models.ForeignKey(help_text='The user who logged in.', on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['user', 'login_at'], name='report_user_user_id_4c01e6_idx')],
            },
        ),
    ]
